Attribute VB_Name = "FolioBundler"
Option Explicit

' ============================================================================
' FolioBundler
' folio の全 VBA コードを 1 つの .bas ファイルにエクスポートする。
' 出力ファイルをインポートして Install_Folio を実行すれば
' 任意の xlsm/xlam にモジュールが復元される。
' ============================================================================

Private Const BUNDLER_MODULE As String = "FolioBundler"
Private Const INSTALLER_MODULE As String = "FolioInstaller"
Private Const SEPARATOR As String = "'>>>MODULE:"
Private Const END_MARKER As String = "'>>>END"

' ----------------------------------------------------------------------------
' Export: 全モジュールを 1 ファイルにバンドル
' ----------------------------------------------------------------------------
Public Sub Folio_Export()
    Dim eh As New ErrorHandler: eh.Enter "FolioBundler", "Folio_Export"
    On Error GoTo ErrHandler

    Dim outPath As String
    outPath = Application.GetSaveAsFilename( _
        InitialFileName:="FolioInstaller.bas", _
        FileFilter:="VBA Module (*.bas),*.bas", _
        title:="Export Folio Installer")
    If outPath = "False" Or Len(outPath) = 0 Then eh.OK: Exit Sub

    Dim buf As String
    buf = GenerateInstaller()

    Dim stm As Object: Set stm = CreateObject("ADODB.Stream")
    stm.Type = 2: stm.Charset = "UTF-8"
    stm.Open
    stm.WriteText buf
    ' Strip BOM
    stm.Position = 0: stm.Type = 1: stm.Position = 3
    Dim out As Object: Set out = CreateObject("ADODB.Stream")
    out.Type = 1: out.Open
    stm.CopyTo out
    out.SaveToFile outPath, 2
    out.Close: stm.Close

    MsgBox "Exported: " & outPath, vbInformation, "Folio Export"
    eh.OK: Exit Sub
ErrHandler: eh.Catch
End Sub

' ----------------------------------------------------------------------------
' Generate the installer module code
' ----------------------------------------------------------------------------
Private Function GenerateInstaller() As String
    Dim eh As New ErrorHandler: eh.Enter "FolioBundler", "GenerateInstaller"
    On Error GoTo ErrHandler
    Dim lines As New Collection

    ' --- Header ---
    lines.Add "Attribute VB_Name = """ & INSTALLER_MODULE & """"
    lines.Add "Option Explicit"
    lines.Add ""
    lines.Add "' ============================================================================"
    lines.Add "' FolioInstaller - Auto-generated by FolioBundler"
    lines.Add "' Generated: " & Format$(Now, "yyyy-mm-dd hh:nn:ss")
    lines.Add "' Run Install_Folio to restore all modules."
    lines.Add "' ============================================================================"
    lines.Add ""

    ' --- Bundled source as a function ---
    lines.Add "Private Function GetBundledSource() As String"
    lines.Add "    Dim s As String"

    ' Collect all module code
    Dim vbc As Object
    For Each vbc In ThisWorkbook.VBProject.VBComponents
        ' Skip ThisWorkbook, Sheet modules, and the installer itself
        If vbc.Type = 100 Then GoTo NextComp  ' Document module
        If vbc.Name = INSTALLER_MODULE Then GoTo NextComp

        Dim compType As Long: compType = vbc.Type
        Dim compName As String: compName = vbc.Name
        Dim codeMod As Object: Set codeMod = vbc.CodeModule
        Dim lineCount As Long: lineCount = codeMod.CountOfLines

        ' Module header: type and name
        lines.Add "    s = s & """ & SEPARATOR & CStr(compType) & ":" & compName & """ & vbLf"

        ' Module code lines
        Dim i As Long
        For i = 1 To lineCount
            Dim srcLine As String: srcLine = codeMod.lines(i, 1)
            ' Skip Attribute lines (restored automatically by VBA)
            If srcLine Like "Attribute *" Then GoTo NextLine
            ' Skip VERSION/BEGIN/END header block for forms
            If compType = 3 Then
                If srcLine Like "VERSION *" Then GoTo NextLine
                If srcLine = "BEGIN" Then GoTo NextLine
                If srcLine Like "  *" And i < 10 Then GoTo NextLine
                If srcLine = "END" And i < 15 Then GoTo NextLine
            End If
            ' Escape quotes
            srcLine = Replace(srcLine, """", """""")
            lines.Add "    s = s & """ & srcLine & """ & vbLf"
NextLine:
        Next i
NextComp:
    Next vbc

    lines.Add "    s = s & """ & END_MARKER & """ & vbLf"
    lines.Add "    GetBundledSource = s"
    lines.Add "End Function"
    lines.Add ""

    ' --- Install sub ---
    lines.Add "Public Sub Install_Folio()"
    lines.Add "    On Error GoTo ErrHandler"
    lines.Add "    Dim vbProj As Object: Set vbProj = ThisWorkbook.VBProject"
    lines.Add "    If vbProj Is Nothing Then"
    lines.Add "        MsgBox ""VBA Project access denied. Enable: Trust Center > Macro Settings > Trust access to VBA project object model"", vbCritical"
    lines.Add "        Exit Sub"
    lines.Add "    End If"
    lines.Add ""
    lines.Add "    ' Parse bundled source"
    lines.Add "    Dim src As String: src = GetBundledSource()"
    lines.Add "    Dim srcLines() As String: srcLines = Split(src, vbLf)"
    lines.Add "    Dim compName As String, compType As Long, compCode As String"
    lines.Add "    Dim inModule As Boolean: inModule = False"
    lines.Add "    Dim installed As Long: installed = 0"
    lines.Add ""
    lines.Add "    Dim i As Long"
    lines.Add "    For i = 0 To UBound(srcLines)"
    lines.Add "        Dim ln As String: ln = srcLines(i)"
    lines.Add "        If Left$(ln, Len(""" & SEPARATOR & """)) = """ & SEPARATOR & """ Then"
    lines.Add "            If inModule Then InstallModule vbProj, compName, compType, compCode: installed = installed + 1"
    lines.Add "            Dim header As String: header = Mid$(ln, Len(""" & SEPARATOR & """) + 1)"
    lines.Add "            compType = CLng(Left$(header, InStr(header, "":"") - 1))"
    lines.Add "            compName = Mid$(header, InStr(header, "":"") + 1)"
    lines.Add "            compCode = """": inModule = True"
    lines.Add "        ElseIf ln = """ & END_MARKER & """ Then"
    lines.Add "            If inModule Then InstallModule vbProj, compName, compType, compCode: installed = installed + 1"
    lines.Add "            inModule = False"
    lines.Add "        ElseIf inModule Then"
    lines.Add "            compCode = compCode & ln & vbCrLf"
    lines.Add "        End If"
    lines.Add "    Next i"
    lines.Add ""
    lines.Add "    ' Create hidden sheets"
    lines.Add "    EnsureConfigSheet ""_folio_config"", Array(""key"", ""value"")"
    lines.Add "    EnsureConfigSheet ""_folio_sources"", Array(""source_name"", ""key_column"", ""display_name_column"", ""mail_link_column"", ""folder_link_column"")"
    lines.Add "    EnsureConfigSheet ""_folio_fields"", Array(""source_name"", ""field_name"", ""type"", ""in_list"", ""editable"", ""multiline"")"
    lines.Add "    EnsureConfigSheet ""_folio_log"", Array(""timestamp"", ""source"", ""key"", ""field"", ""old_value"", ""new_value"", ""origin"")"
    lines.Add ""
    lines.Add "    ' Clean up installer module"
    lines.Add "    On Error Resume Next"
    lines.Add "    vbProj.VBComponents.Remove vbProj.VBComponents(""" & INSTALLER_MODULE & """)"
    lines.Add "    On Error GoTo 0"
    lines.Add ""
    lines.Add "    MsgBox ""Folio installed ("" & installed & "" modules). Run Alt+F8 > Folio_ShowPanel"", vbInformation"
    lines.Add "    Exit Sub"
    lines.Add "ErrHandler:"
    lines.Add "    MsgBox ""Install error: "" & Err.Description, vbCritical"
    lines.Add "End Sub"
    lines.Add ""

    ' --- InstallModule helper ---
    lines.Add "Private Sub InstallModule(vbProj As Object, compName As String, compType As Long, code As String)"
    lines.Add "    On Error Resume Next"
    lines.Add "    ' Remove existing module with same name"
    lines.Add "    Dim existing As Object: Set existing = vbProj.VBComponents(compName)"
    lines.Add "    If Not existing Is Nothing Then"
    lines.Add "        If existing.Type <> 100 Then vbProj.VBComponents.Remove existing"
    lines.Add "    End If"
    lines.Add "    On Error GoTo 0"
    lines.Add ""
    lines.Add "    Dim comp As Object: Set comp = vbProj.VBComponents.Add(compType)"
    lines.Add "    comp.Name = compName"
    lines.Add "    Dim codeMod As Object: Set codeMod = comp.CodeModule"
    lines.Add "    If codeMod.CountOfLines > 0 Then codeMod.DeleteLines 1, codeMod.CountOfLines"
    lines.Add "    codeMod.AddFromString code"
    lines.Add "End Sub"
    lines.Add ""

    ' --- EnsureConfigSheet helper ---
    lines.Add "Private Sub EnsureConfigSheet(sheetName As String, headers As Variant)"
    lines.Add "    On Error Resume Next"
    lines.Add "    Dim ws As Object: Set ws = ThisWorkbook.Worksheets(sheetName)"
    lines.Add "    On Error GoTo 0"
    lines.Add "    If Not ws Is Nothing Then Exit Sub"
    lines.Add "    Set ws = ThisWorkbook.Worksheets.Add(After:=ThisWorkbook.Worksheets(ThisWorkbook.Worksheets.Count))"
    lines.Add "    ws.Name = sheetName"
    lines.Add "    ws.Visible = 2  ' xlSheetVeryHidden"
    lines.Add "    Dim i As Long"
    lines.Add "    For i = 0 To UBound(headers)"
    lines.Add "        ws.Cells(1, i + 1).Value = headers(i)"
    lines.Add "    Next i"
    lines.Add "End Sub"

    ' --- Join all lines ---
    Dim result As String
    Dim item As Variant
    For Each item In lines
        result = result & CStr(item) & vbCrLf
    Next item
    GenerateInstaller = result
    eh.OK: Exit Function
ErrHandler: eh.Catch
End Function

